[package]
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
categories = ["multimedia::images"]
description = "Smart filter to remove Floyd-Steinberg dithering from paletted images"
license = "AGPL-3.0+"
name = "undither"
readme = "README.md"
version = "1.0.0"

[[bin]]
doc = false
name = "undither"
path = "src/bin.rs"
required-features = ["binary"]

[dependencies]
imgref = "1.2.2"
itertools = "0.5.9"
loop9 = "0.1.1"
rgb = "0.7.2"
vpsearch = "1.3.2"

[dependencies.lodepng]
optional = true
version = "2.0.0"

[features]
binary = ["lodepng"]
